services:
  app:
    build: .
    container_name: ev-forecast-sim
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "5000:5000"  
    environment:
      - USER=admin
      - USERNAME=admin
      - LOGNAME=admin
      - METAFLOW_USER=admin
      - MLFLOW_TRACKING_URI=http://localhost:5000
      - PYTHONPATH=/app
    stdin_open: true
    tty: true
